package com.mediaforge.app.subs

import java.util.Locale

/** One `Key: Value` line of a header section. key == "" keeps a comment/other line verbatim in [value]. */
data class InfoLine(val key: String, val value: String)

/** An embedded font/graphic (ASS [Fonts]/[Graphics]); [lines] stay uuencoded so round trips are lossless. */
data class Attachment(val section: String, val name: String, val lines: List<String>)

/** Style colours are Android ARGB ints (alpha 255 = opaque); ASS stores them as &HAABBGGRR with 00 = opaque. */
data class AssStyle(
    val name: String = "Default",
    val fontName: String = "Arial",
    val fontSize: Float = 48f,
    val primary: Int = 0xFFFFFFFF.toInt(),
    val secondary: Int = 0xFFFF0000.toInt(),
    val outline: Int = 0xFF000000.toInt(),
    val back: Int = 0xFF000000.toInt(),
    val bold: Boolean = false,
    val italic: Boolean = false,
    val underline: Boolean = false,
    val strikeOut: Boolean = false,
    val scaleX: Float = 100f,
    val scaleY: Float = 100f,
    val spacing: Float = 0f,
    val angle: Float = 0f,
    val borderStyle: Int = 1,      // 1 = outline + shadow, 3 = opaque box
    val outlineWidth: Float = 2f,
    val shadow: Float = 2f,
    val alignment: Int = 2,        // numpad layout 1..9
    val marginL: Int = 10,
    val marginR: Int = 10,
    val marginV: Int = 10,
    val encoding: Int = 1,
)

/** Times are milliseconds (ASS files only keep centiseconds). */
data class AssEvent(
    val comment: Boolean = false,
    val layer: Int = 0,
    val startMs: Long = 0L,
    val endMs: Long = 2000L,
    val style: String = "Default",
    val actor: String = "",
    val marginL: Int = 0,
    val marginR: Int = 0,
    val marginV: Int = 0,
    val effect: String = "",
    val text: String = "",
) {
    val durationMs: Long get() = endMs - startMs
}

/** A whole subtitle script. ASS is the internal model; every other format maps to and from it. */
data class SubFile(
    val info: List<InfoLine> = emptyList(),
    val garbage: List<InfoLine> = emptyList(),          // [Aegisub Project Garbage]
    val styles: List<AssStyle> = listOf(AssStyle()),
    val events: List<AssEvent> = emptyList(),
    val attachments: List<Attachment> = emptyList(),
    val extradata: List<String> = emptyList(),
    val otherSections: List<Pair<String, List<String>>> = emptyList(),
) {
    fun info(key: String): String? = info.firstOrNull { it.key.equals(key, true) }?.value

    fun withInfo(key: String, value: String): SubFile {
        val has = info.any { it.key.equals(key, true) }
        val list = if (has) info.map { if (it.key.equals(key, true)) InfoLine(it.key, value) else it } else info + InfoLine(key, value)
        return copy(info = list)
    }

    private val resX: Int? get() = info("PlayResX")?.trim()?.toIntOrNull()
    private val resY: Int? get() = info("PlayResY")?.trim()?.toIntOrNull()

    /** libass rule: both missing -> 384x288; one missing -> derived with 4:3. */
    val playResX: Int get() = resX ?: resY?.let { it * 4 / 3 } ?: 384
    val playResY: Int get() = resY ?: resX?.let { it * 3 / 4 } ?: 288
    val wrapStyle: Int get() = info("WrapStyle")?.trim()?.toIntOrNull() ?: 0
    val scaledBorderAndShadow: Boolean get() = info("ScaledBorderAndShadow")?.trim()?.equals("yes", true) ?: false

    fun style(name: String): AssStyle? = styles.firstOrNull { it.name == name } ?: styles.firstOrNull()

    companion object {
        fun blank(width: Int = 1280, height: Int = 720) = SubFile(
            info = listOf(
                InfoLine("", "; Script generated by MediaForge"),
                InfoLine("ScriptType", "v4.00+"),
                InfoLine("WrapStyle", "0"),
                InfoLine("ScaledBorderAndShadow", "yes"),
                InfoLine("PlayResX", width.toString()),
                InfoLine("PlayResY", height.toString()),
            ),
        )
    }
}

// ---------------------------------------------------------------- colours and times

/** Parses `&HAABBGGRR`, `&HBBGGRR&` or an old-style decimal number into an Android ARGB int. */
fun parseAssColor(s: String): Int {
    val t = s.trim()
    val v: Long = try {
        when {
            t.startsWith("&H", true) -> t.substring(2).trimEnd('&').toLong(16)
            t.startsWith("0x", true) -> t.substring(2).toLong(16)
            else -> t.toLong()
        }
    } catch (e: NumberFormatException) {
        return 0xFFFFFFFF.toInt()
    }
    val a = 255 - ((v shr 24) and 0xFF).toInt()
    val b = ((v shr 16) and 0xFF).toInt()
    val g = ((v shr 8) and 0xFF).toInt()
    val r = (v and 0xFF).toInt()
    return (a shl 24) or (r shl 16) or (g shl 8) or b
}

fun formatAssColor(argb: Int): String {
    val a = 255 - ((argb ushr 24) and 0xFF)
    val r = (argb shr 16) and 0xFF
    val g = (argb shr 8) and 0xFF
    val b = argb and 0xFF
    return "&H%02X%02X%02X%02X".format(Locale.US, a, b, g, r)
}

private val ASS_TIME = Regex("""(\d+):(\d{1,2}):(\d{1,2})(?:[.,](\d*))?""")

/** `H:MM:SS.cc` (also tolerates 1 or 3 fraction digits) -> milliseconds. */
fun parseAssTime(s: String): Long? {
    val m = ASS_TIME.matchEntire(s.trim()) ?: return null
    val (h, mi, se, frac) = m.destructured
    val ms = when (frac.length) {
        0 -> 0
        1 -> frac.toInt() * 100
        2 -> frac.toInt() * 10
        else -> frac.take(3).toInt()
    }
    return ((h.toLong() * 60 + mi.toLong()) * 60 + se.toLong()) * 1000 + ms
}

/** Milliseconds -> `H:MM:SS.cc`, rounded to centiseconds like Aegisub. */
fun formatAssTime(ms: Long): String {
    val cs = (ms.coerceAtLeast(0L) + 5) / 10
    return "%d:%02d:%02d.%02d".format(Locale.US, cs / 360000, (cs / 6000) % 60, (cs / 100) % 60, cs % 100)
}

/** Whole-number floats print as ints, others with up to 2 decimals (ASS style numbers). */
fun formatAssNumber(f: Float): String =
    if (f % 1f == 0f) f.toInt().toString() else "%.2f".format(Locale.US, f).trimEnd('0').trimEnd('.')
